#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the rotLeft function below.
def rotLeft(a, d):
        #nd = input().split()

        
        b=[]
        i=0
        k=0
        n=len(a)
        #print(a[-0])

        while n!=0:
            if len(b)==len(a):
                break
            if d==n:
                b.append(a[k])
                k+=1
                continue
            
            b.append(a[i+d])
            i+=1
            n-=1
        
        return b

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))

            
    

    result = rotLeft(a, d)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
